version: 3 # don't touch

# ****************************** #

# Each <tick> will create or load a world.
# If you have a lot of players, a lower value is recommended,
# but if your server is slow, a higher value is recommended.
# 20 ticks 1 world per second.
# 10 ticks 2 worlds per second.
# 5 ticks 4 worlds per second.
# 1 tick 20 worlds per second.
queue-period: 10

# World inactivity time for unload.
# Disabling or a high value may overload the server.
# Default: 900 seconds (15 minutes).
# Recommended: >600 seconds (10 minutes).
# Disabled: 0 seconds (Not recommended).
inactivity-time: 900 # seconds

# * WORLD SECTION *

# Directory (folder name) of the template that will be used when the player creates a world.
world-template: 'worldtemplate'

# The limit of the world that the player can break and build.
world-limit:
    x: 64
    y: 64
    ny: 0
    z: 64

void-teleport: -20

default-spawn-location:
    x: 0
    y: 10
    z: 0

# Note: Case-insensitive: does not matter if uppercase or lowercase.
game-rules:
    - 'doDaylightCycle true'
    # - 'keepInventory false'
    # - 'doMobSpawning false'
    # - 'doWeatherCycle false'
    # - 'doMobLoot false'
    # - 'fallDamage false'

default-world-options:
    - 'visibility false'
    - 'pvp false'

multi-member: true
view-distance: 8
simulation-distance: 8
world-border: 200

# * END OF WORLD SECTION * #

# * STORAGE SECTION *

# Options:
#   - h2
#   - mysql
storage-method: h2

# Change this to use mysql.
storage-method-config:
    address: localhost
    port: 3306
    username: root
    password: ''
    database: minecraft
    ssl: false
    maximum-pool-size: 10

# Options:
#   - local
#   - ftp
world-storage-method: local

ftp-config:
    address: localhost
    port: 21
    username: root
    password: ''
    remote-directory: /worlds
    passive-mode: true
    tls: false

# * END OF STORAGE SECTION * #

# If you don't want to see too many messages in the console, don't touch this.
debug: false
