name: GPrivateWorlds
version: '${version}'
main: org.giancpz.gprivateworlds.Main
api-version: '1.13'

commands:
    gprivateworlds:
        description: privateworld
        aliases: pw
        usage: /<command> <create|home|visit|accept|invite|kick|leave|setspawn|delete>

permissions:
    gprivateworlds.user:
        description: Normal user permission
        default: true
    gprivateworlds.template.edit:
        description: Template edit permission
        default: op
